
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      DB: ${DB_NAME:-app}
      # You should definitely change the password in production
      PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
      USER: ${DB_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${DB:-app}", "-U", "${USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> sensiolabs/gotenberg-bundle ###
  gotenberg:
    image: 'gotenberg/gotenberg:8'
###< sensiolabs/gotenberg-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
