<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423163046 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE credited_person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, person_type_id INT NOT NULL, sheet_id INT NOT NULL, person_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_71F46BD1E7D23F1A ON credited_person (person_type_id)');
        $this->addSql('CREATE INDEX IDX_71F46BD18B1206A5 ON credited_person (sheet_id)');
        $this->addSql('CREATE INDEX IDX_71F46BD1217BBB47 ON credited_person (person_id)');
        $this->addSql('CREATE TABLE member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(100) NOT NULL, name VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_70E4FA78E7927C74 ON member (email)');
        $this->addSql('CREATE TABLE person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE person_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE set_list_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, name VARCHAR(100) NOT NULL, notes TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, setlist_id INT NOT NULL, sheet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2835F3D60D8C499 ON set_list_item (setlist_id)');
        $this->addSql('CREATE INDEX IDX_2835F3D8B1206A5 ON set_list_item (sheet_id)');
        $this->addSql('CREATE TABLE setlist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, date DATE DEFAULT NULL, notes TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE sheet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, tags TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, refs TEXT DEFAULT NULL, files json NOT NULL, full_path VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE web_dav_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hashed_token VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CE1EACE27597D3FE ON web_dav_token (member_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE credited_person ADD CONSTRAINT FK_71F46BD1E7D23F1A FOREIGN KEY (person_type_id) REFERENCES person_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE credited_person ADD CONSTRAINT FK_71F46BD18B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE credited_person ADD CONSTRAINT FK_71F46BD1217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE set_list_item ADD CONSTRAINT FK_2835F3D60D8C499 FOREIGN KEY (setlist_id) REFERENCES setlist (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE set_list_item ADD CONSTRAINT FK_2835F3D8B1206A5 FOREIGN KEY (sheet_id) REFERENCES sheet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE web_dav_token ADD CONSTRAINT FK_CE1EACE27597D3FE FOREIGN KEY (member_id) REFERENCES member (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE credited_person DROP CONSTRAINT FK_71F46BD1E7D23F1A');
        $this->addSql('ALTER TABLE credited_person DROP CONSTRAINT FK_71F46BD18B1206A5');
        $this->addSql('ALTER TABLE credited_person DROP CONSTRAINT FK_71F46BD1217BBB47');
        $this->addSql('ALTER TABLE set_list_item DROP CONSTRAINT FK_2835F3D60D8C499');
        $this->addSql('ALTER TABLE set_list_item DROP CONSTRAINT FK_2835F3D8B1206A5');
        $this->addSql('ALTER TABLE web_dav_token DROP CONSTRAINT FK_CE1EACE27597D3FE');
        $this->addSql('DROP TABLE credited_person');
        $this->addSql('DROP TABLE member');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE person_type');
        $this->addSql('DROP TABLE set_list_item');
        $this->addSql('DROP TABLE setlist');
        $this->addSql('DROP TABLE sheet');
        $this->addSql('DROP TABLE web_dav_token');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
